#
# Definition of all trackable objects
# Identifier corresponds to Trackable ID set in Tracking Tools
#
rigid_bodies:
    '1':
        pose: Drone/pose
        pose2d: Drone/ground_pose
        child_frame_id: Drone/base_link
        parent_frame_id: world
optitrack_config:
        multicast_address: 224.0.0.1
